### ISSUE TITLE
各依赖有版本要求吗？一执行就退出来了

### ISSUE THREAD

**Issue by Chersh-Pan** [xinzhen2015/Donkey#1]
platform darwin -- Python 3.7.2, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: /Users/panjiaxu/Downloads/Donkey-master/Python, inifile:
plugins: xdist-1.14, rerunfailures-6.0, parallel-0.0.9, metadata-1.8.0, html-1.20.0, cov-2.3.0
collecting 1 item                                                                                        INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 210, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 259, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 487, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 251, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_funcarg__cov' in plugin <module 'pytest_cov.plugin' from '/usr/local/lib/python3.7/site-packages/pytest_cov/plugin.py'>

**Comment by xinzhen2015** [comment]
[我的环境截图](https://github.com/xinzhen2015/Donkey/blob/master/屏幕快照%202019-03-13%20下午8.52.51.png)

#### 不好意思啊，回复的比较晚~
#### 目前我这边运行正常，看你的报错是和 Pytest 的版本有关系，具体原因还不明朗。
#### 你可以尝试换一下 Pytest 的版本，

> 另外要跑起来Donkey，要确保Appim先启动，如果是在真机上跑，要确保Appium 自带的WebDriverAgent是配置好的。
